image: openjdk:8-jdk

variables:
  ANDROID_COMPILE_SDK: "28"
  ANDROID_BUILD_TOOLS: "28.0.2"
  ANDROID_SDK_TOOLS:   "4333796"

before_script:
  - apt-get --quiet update --yes

stages:
  - danger

danger:
  stage: danger
  script:
    - apt-get --quiet install --yes ruby-bundler
    - apt-get --quiet install --yes ruby-dev
    - apt-get --quiet install --yes build-essential
    - gem install bundler
    - bundle install
    - ./gradlew runChecksForDanger
    - bundle exec danger